language: python

sudo: enabled


before_script:
  - psql -c 'create database pytestponyorm;' -U postgres
  - psql -c "CREATE USER j WITH PASSWORD 'j;'" -U postgres
  - psql -c "GRANT ALL ON DATABASE pytestponyorm TO j;" -U postgres

branches:
  only:
  - master
  - dev
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-sqlite
    - python: 3.5
      env: TOXENV=py35-pgsql
    - python: 3.5
      env: TOXENV=flake8

    - python: 3.6
      env: TOXENV=py36-sqlite
    - python: 3.6
      env: TOXENV=py36-pgsql
    - python: 3.6
      env: TOXENV=flake8


install:
  - pip install tox

script:
  - tox -e $TOXENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
